### ISSUE TITLE
Password Change Activity: Empty string input but it succeeds to change password.

### ISSUE THREAD

**Issue by KangDroid** [JournalMP6/TodayDiary#12]
If we input empty string on password change activity[all of fields are set to ""]  -> It just sends communication to server and change password as empty.

Since password set to empty on passwordChangeActivity, we are locked out because LoginActivity won't let us enter empty string.

Therefore UI should check for password integrity on PasswordChangeActivity.

**Comment by PangHae** [comment]
issue solved
