### ISSUE TITLE
Profile: We need to go back to login page if user removed their account.

### ISSUE THREAD

**Issue by KangDroid** [JournalMP6/TodayDiary#13]
Current behavior: User remove their account and view is still on profile activity. If we push back button or if we trying to contact server requiring user token, server will throw 404 or 403[forbidden] error to client. 

What it should be is: After removing account, we need to invalidate server token first[handled in server-repository] and view should return to login page.

- So view need to return to login activity straight after removing their account.

**Comment by PangHae** [comment]
issue solved
