### ISSUE TITLE
LockActivity가 필요하지 않은 곳에서 발생

### ISSUE THREAD

**Issue by azzyjk** [JournalMP6/TodayDiary#23]
MapActvity에서 선택 후 돌아올 때
JoinActivity에서 계정 생성 후 돌아올 때
FollowActvitiy에서 UserSearchFragment로 돌아올 때
PrimaryLockActivity에서 비밀번호 생성 후 돌아올 때
MainFragment에서 뒤로가기 버튼을 눌렀을 때

**Comment by KangDroid** [comment]
@LeeGwangHae , @azzyjk , @KvngSungBum 

이거 보면 라이프사이클 파악을 우리가 제대로 못했거나[i.e 엑티비티가 재생될 때 vs Recent/Home Button 클릭시 사이클] 아니면 따로 Boolean값들을 걸어줘서 인텐트를 따야될거 같은데

각 엑티비티에서 인텐트가 일어나면 안되는 상황일 때, 특정 불린값 정의해서 그걸 false로 만들어놓고, SuperActivity에서 체크하면서 인텐트 처리하는거는 어떨까요?
